services:
  - type: web
    name: law-simulation-backend
    runtime: python
    rootDir: "law de/backend"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    plan: free
  - type: web
    runtime: static
    name: law-simulation-frontend
    rootDir: "law de/frontend"
    buildCommand: VITE_API_BASE_URL="https://${BACKEND_HOST}.onrender.com" npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: law-simulation-backend
          property: host
